name: 'Saltstack'

on: [push, pull_request]

jobs:
  saltstack-bionic:
    name: 'Saltstack (Ubuntu 18.04 LTS)'
    runs-on: ubuntu-18.04
    steps:
    - name: Install Chef Inspec
      run: |
        wget https://packages.chef.io/files/stable/inspec/4.26.4/ubuntu/18.04/inspec_4.26.4-1_amd64.deb
        sudo dpkg -i inspec_4.26.4-1_amd64.deb
        rm inspec_4.26.4-1_amd64.deb
        sudo inspec --chef-license=accept-silent

    - name: Install salt-minion
      run: |
        wget -O - http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
        echo "deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main" | sudo tee /etc/apt/sources.list.d/saltstack.list
        sudo apt-get update
        sudo apt-get install -y salt-minion

    - uses: actions/checkout@v1
    - name: Apply state
      run: |
        sudo mkdir /srv/sshd
        sudo cp -r * /srv/sshd
        sudo salt-call state.apply \
          --local --log-file=/dev/null --retcode-passthrough --file-root /srv --pillar-root \
          /srv/sshd/tests/pillar sshd

    - name: Run inspec
      run: sudo inspec exec tests/integration/sshd

  saltstack-xenial:
    name: 'Saltstack (Ubuntu 16.04 LTS)'
    runs-on: ubuntu-16.04
    steps:
    - name: Install Chef Inspec
      run: |
        wget https://packages.chef.io/files/stable/inspec/4.26.4/ubuntu/16.04/inspec_4.26.4-1_amd64.deb
        sudo dpkg -i inspec_4.26.4-1_amd64.deb
        rm inspec_4.26.4-1_amd64.deb
        sudo inspec --chef-license=accept-silent

    - name: Install salt-minion
      run: |
        wget -O - http://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
        echo "deb http://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest xenial main" | sudo tee /etc/apt/sources.list.d/saltstack.list
        sudo apt-get update
        sudo apt-get install -y salt-minion

    - uses: actions/checkout@v1
    - name: Apply state
      run: |
        sudo mkdir /srv/sshd
        sudo cp -r * /srv/sshd
        sudo salt-call state.apply \
          --local --log-file=/dev/null --retcode-passthrough --file-root /srv --pillar-root \
          /srv/sshd/tests/pillar sshd

    - name: Run inspec
      run: sudo inspec exec tests/integration/sshd
