name: 'Saltstack'

on: [push, pull_request]

jobs:
  saltstack-jammy:
    name: 'Saltstack (Ubuntu 22.04 LTS)'
    runs-on: ubuntu-22.04
    steps:
    - name: Install Chef Inspec
      run: |
        # NOTE: Newer inspec versions require a license, so keeping 5.x
        # NOTE: Chef doesn't provide a package for 22.04
        wget https://packages.chef.io/files/stable/inspec/5.22.36/ubuntu/20.04/inspec_5.22.36-1_amd64.deb
        sudo dpkg -i inspec_5.22.36-1_amd64.deb
        rm inspec_5.22.36-1_amd64.deb
        sudo inspec --chef-license=accept-silent

    - name: Install salt-minion
      run: |
        sudo wget -O /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
        echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main" | sudo tee /etc/apt/sources.list.d/salt.list
        sudo apt-get update
        sudo apt-get install -y salt-minion

    - uses: actions/checkout@v1
    - name: Apply state
      run: |
        sudo mkdir /srv/sshd
        sudo cp -r * /srv/sshd
        sudo salt-call state.apply \
          --local --log-file=/dev/null --retcode-passthrough --file-root /srv --pillar-root \
          /srv/sshd/tests/pillar sshd

    - name: Run inspec
      run: sudo inspec exec tests/integration/sshd

  saltstack-focal:
    name: 'Saltstack (Ubuntu 20.04 LTS)'
    runs-on: ubuntu-20.04
    steps:
    - name: Install Chef Inspec
      run: |
        # NOTE: Newer inspec versions require a license, so keeping 5.x
        wget https://packages.chef.io/files/stable/inspec/5.22.36/ubuntu/20.04/inspec_5.22.36-1_amd64.deb
        sudo dpkg -i inspec_5.22.36-1_amd64.deb
        rm inspec_5.22.36-1_amd64.deb
        sudo inspec --chef-license=accept-silent

    - name: Install salt-minion
      run: |
        sudo wget -O /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
        echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/latest focal main" | sudo tee /etc/apt/sources.list.d/salt.list
        sudo apt-get update
        sudo apt-get install -y salt-minion

    - uses: actions/checkout@v1
    - name: Apply state
      run: |
        sudo mkdir /srv/sshd
        sudo cp -r * /srv/sshd
        sudo salt-call state.apply \
          --local --log-file=/dev/null --retcode-passthrough --file-root /srv --pillar-root \
          /srv/sshd/tests/pillar sshd

    - name: Run inspec
      run: sudo inspec exec tests/integration/sshd
